#include <FastLED.h>

// Define our LED PINS based off each GRID for both PLAYERS
#define NUM_LEDS     9 // Change this to the number of LEDs in your strips
#define BRIGHTNESS  5  // LED brightness

#define COLOR_ON    CRGB::White   // Color when LED is ON
#define COLOR_OFF   CRGB::Red   // Color when LED is OFF

// Player 1 Bottom Screen
// TOP OF SCREEN
#define LEDPLAYER1_BOTTOMPIN1     2
#define LEDPLAYER1_BOTTOMPIN2     3
#define LEDPLAYER1_BOTTOMPIN3     4
#define LEDPLAYER1_BOTTOMPIN4     5
#define LEDPLAYER1_BOTTOMPIN5     6
#define LEDPLAYER1_BOTTOMPIN6     7
#define LEDPLAYER1_BOTTOMPIN7     8
#define LEDPLAYER1_BOTTOMPIN8     9
#define LEDPLAYER1_BOTTOMPIN9     10
// BOTTOM OF SCREEN

// Player 1 Top Screen
// TOP OF SCREEN
#define LEDPLAYER1_TOPPIN1     22
#define LEDPLAYER1_TOPPIN2     23
#define LEDPLAYER1_TOPPIN3     24
#define LEDPLAYER1_TOPPIN4     25
#define LEDPLAYER1_TOPPIN5     26
#define LEDPLAYER1_TOPPIN6     27
#define LEDPLAYER1_TOPPIN7     28
#define LEDPLAYER1_TOPPIN8     29
#define LEDPLAYER1_TOPPIN9     30
// BOTTOM OF SCREEN

// Player 2 Bottom Screen
// TOP OF SCREEN
#define LEDPLAYER2_BOTTOMPIN1     53
#define LEDPLAYER2_BOTTOMPIN2     52
#define LEDPLAYER2_BOTTOMPIN3     51
#define LEDPLAYER2_BOTTOMPIN4     50
#define LEDPLAYER2_BOTTOMPIN5     49
#define LEDPLAYER2_BOTTOMPIN6     48
#define LEDPLAYER2_BOTTOMPIN7     47
#define LEDPLAYER2_BOTTOMPIN8     46
#define LEDPLAYER2_BOTTOMPIN9     45
// BOTTOM OF SCREEN

// Player 2 Top Screen
// TOP OF SCREEN
#define LEDPLAYER2_TOPPIN1     41
#define LEDPLAYER2_TOPPIN2     40
#define LEDPLAYER2_TOPPIN3     39
#define LEDPLAYER2_TOPPIN4     38
#define LEDPLAYER2_TOPPIN5     37
#define LEDPLAYER2_TOPPIN6     36
#define LEDPLAYER2_TOPPIN7     35
#define LEDPLAYER2_TOPPIN8     34
#define LEDPLAYER2_TOPPIN9     33
// BOTTOM OF SCREEN

// Global LED arrays
CRGB ledsPLAYER1TOP[9][NUM_LEDS];
CRGB ledsPLAYER1BOTTOM[9][NUM_LEDS];
CRGB ledsPLAYER2TOP[9][NUM_LEDS];
CRGB ledsPLAYER2BOTTOM[9][NUM_LEDS];


void setup() {
    // Initialize our LED Grids
    
    // Player 1 Bottom Screen
    FastLED.addLeds<WS2812B, LEDPLAYER1_BOTTOMPIN1, GRB>(ledsPLAYER1BOTTOM[0], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_BOTTOMPIN2, GRB>(ledsPLAYER1BOTTOM[1], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_BOTTOMPIN3, GRB>(ledsPLAYER1BOTTOM[2], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_BOTTOMPIN4, GRB>(ledsPLAYER1BOTTOM[3], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_BOTTOMPIN5, GRB>(ledsPLAYER1BOTTOM[4], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_BOTTOMPIN6, GRB>(ledsPLAYER1BOTTOM[5], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_BOTTOMPIN7, GRB>(ledsPLAYER1BOTTOM[6], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_BOTTOMPIN8, GRB>(ledsPLAYER1BOTTOM[7], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_BOTTOMPIN9, GRB>(ledsPLAYER1BOTTOM[8], NUM_LEDS);
    // Player 1 Top Screen
    FastLED.addLeds<WS2812B, LEDPLAYER1_TOPPIN1, GRB>(ledsPLAYER1TOP[0], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_TOPPIN2, GRB>(ledsPLAYER1TOP[1], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_TOPPIN3, GRB>(ledsPLAYER1TOP[2], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_TOPPIN4, GRB>(ledsPLAYER1TOP[3], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_TOPPIN5, GRB>(ledsPLAYER1TOP[4], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_TOPPIN6, GRB>(ledsPLAYER1TOP[5], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_TOPPIN7, GRB>(ledsPLAYER1TOP[6], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_TOPPIN8, GRB>(ledsPLAYER1TOP[7], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER1_TOPPIN9, GRB>(ledsPLAYER1TOP[8], NUM_LEDS);

    // Player 2 Bottom Screen
    FastLED.addLeds<WS2812B, LEDPLAYER2_BOTTOMPIN1, GRB>(ledsPLAYER2BOTTOM[0], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_BOTTOMPIN2, GRB>(ledsPLAYER2BOTTOM[1], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_BOTTOMPIN3, GRB>(ledsPLAYER2BOTTOM[2], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_BOTTOMPIN4, GRB>(ledsPLAYER2BOTTOM[3], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_BOTTOMPIN5, GRB>(ledsPLAYER2BOTTOM[4], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_BOTTOMPIN6, GRB>(ledsPLAYER2BOTTOM[5], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_BOTTOMPIN7, GRB>(ledsPLAYER2BOTTOM[6], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_BOTTOMPIN8, GRB>(ledsPLAYER2BOTTOM[7], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_BOTTOMPIN9, GRB>(ledsPLAYER2BOTTOM[8], NUM_LEDS);

    // Player 2 Top Screen
    FastLED.addLeds<WS2812B, LEDPLAYER2_TOPPIN1, GRB>(ledsPLAYER2TOP[0], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_TOPPIN2, GRB>(ledsPLAYER2TOP[1], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_TOPPIN3, GRB>(ledsPLAYER2TOP[2], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_TOPPIN4, GRB>(ledsPLAYER2TOP[3], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_TOPPIN5, GRB>(ledsPLAYER2TOP[4], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_TOPPIN6, GRB>(ledsPLAYER2TOP[5], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_TOPPIN7, GRB>(ledsPLAYER2TOP[6], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_TOPPIN8, GRB>(ledsPLAYER2TOP[7], NUM_LEDS);
    FastLED.addLeds<WS2812B, LEDPLAYER2_TOPPIN9, GRB>(ledsPLAYER2TOP[8], NUM_LEDS);


    FastLED.setBrightness(BRIGHTNESS);
}

// LEDs begin at 
void loop() {
  lightUpLED();

  delay(1000);

  lightdownLED();

  delay(500);


  
}

// Function to light up the LED at given row and column
void lightUpLED() {
  // Turn off all LEDs
  FastLED.clear();
  for(int i=0; i<9;++i){
    for(int j=0;j<9;++j){
        ledsPLAYER1TOP[i][j]= COLOR_ON;
        ledsPLAYER1BOTTOM[i][j]= COLOR_ON;
        ledsPLAYER2TOP[i][j]= COLOR_ON;
        ledsPLAYER2BOTTOM[i][j]= COLOR_ON;
    }
  }
  // Turn on the specified LED


  // Show the LEDs
  FastLED.show();
  }

  // Function to light up the LED at given row and column and turn it blue
void lightdownLED() {
  // Turn off all LEDs
  FastLED.clear();
  for(int i=0; i<9;++i){
    for(int j=0;j<9;++j){
        ledsPLAYER1TOP[i][j]= COLOR_OFF;
        ledsPLAYER1BOTTOM[i][j]= COLOR_OFF;
        ledsPLAYER2TOP[i][j]= COLOR_OFF;
        ledsPLAYER2BOTTOM[i][j]= COLOR_OFF;
    }
  }
  // Turn on the specified LED


  // Show the LEDs
  FastLED.show();
  }